# Generated by Django 3.2.16 on 2022-12-02 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20221201_0624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_of_questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voted_by',
        ),
        migrations.AddField(
            model_name='question',
            name='description2',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 2, 48, 19, 336597), verbose_name='Время жизни'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(default='default.jpg', null=True, upload_to='images/question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
