# Generated by Django 3.2.16 on 2022-12-02 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20221202_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='life_time',
        ),
        migrations.AddField(
            model_name='question',
            name='ex_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 3, 59, 36, 208500), verbose_name='Время жизни'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 3, 59, 36, 208485)),
        ),
    ]
