# Generated by Django 3.2.16 on 2022-12-06 05:46

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20221202_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='проголосовавшие'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ex_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 5, 46, 10, 804571), verbose_name='Время жизни'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 5, 46, 10, 804556)),
        ),
    ]
