# Generated by Django 3.2.16 on 2022-12-06 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20221206_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ex_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 6, 50, 6, 269821), verbose_name='Время жизни'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 6, 50, 6, 269808)),
        ),
    ]
